image: "debian-jessie-debuild"

stages:
    - build

# https://blog.adfinis-sygroup.ch/de/automated-debian-packagebuild-gitlabci/
# https://docs.gitlab.com/ce/ci/yaml/README.html
package:
    stage: build
    script:
        - dch -l "-$(date +%s)" "autobuild master"
        - debuild binary
        - mkdir build
        - mv ../*.deb build
    artifacts:
        paths:
            - build/*.deb

