image: "debian:latest"

before_script:
    - apt-get update -q
    - apt-get -y upgrade
    - apt-get --no-install-recommends -y install python-support debhelper devscripts


package:
    stage: build
    script:
        - dch -l "-$(date +%s)" "autobuild master"
        - debuild binary
